### ISSUE TITLE
allow initadcirc to work with user-installed git on queenbee2

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#455] opened 2021-04-14 20:47 UTC
The LONI Queenbee2 platform uses an old version of git that no longer works with github. As a result, a user-installed git client is required to interact with GitHub on Queenbee2. Right now, we can work around this by downloading the adcirc repo manually and then executing initadcirc in the asgs shell. Not sure what the best automatic solution is to automating this.

**Comment by wwlwpd** [comment] 2021-04-14 22:41
This should be fixed with a request to support to upgrade, I'll reproduce the issue and will issue the request. And we'll track it here.

**Comment by wwlwpd** [comment] 2021-04-14 22:46
@jasonfleming - I can't reproduce this; can you let me know what steps you used to reproduce this?

```
@qb1 tmp]$ git --version
git version 1.7.1
```

```
[@qb1 tmp]$ git clone git@github.com:jasonfleming/asgs.git
Initialized empty Git repository in /tmp/asgs/.git/
remote: Enumerating objects: 667, done.
remote: Counting objects: 100% (667/667), done.
remote: Compressing objects: 100% (298/298), done.
remote: Total 20563 (delta 401), reused 597 (delta 358), pack-reused 19896
Receiving objects: 100% (20563/20563), 132.40 MiB | 27.39 MiB/s, done.
Resolving deltas: 100% (16064/16064), done.
[@qb1 tmp]$ rm -rf asgs/
[@qb1 tmp]$ git clone https://github.com/jasonfleming/asgs.git
Initialized empty Git repository in /tmp/asgs/.git/
remote: Enumerating objects: 667, done.
remote: Counting objects: 100% (667/667), done.
remote: Compressing objects: 100% (298/298), done.
remote: Total 20563 (delta 401), reused 597 (delta 358), pack-reused 19896
Receiving objects: 100% (20563/20563), 132.40 MiB | 18.72 MiB/s, done.
Resolving deltas: 100% (16064/16064), done.
```

**Comment by wwlwpd** [comment] 2021-04-14 23:25
Is this the error?

```
Initialized empty Git repository in /tmp/adcirc-cg/.git/
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/adcirc/adcirc-cg.git/info/refs
```

If so, it's not tied to a `git` version; GH is deprecating their https URI.

`git@github.com:adcirc/adcirc-cg.git` should work,

```
git clone git@github.com:adcirc/adcirc-cg.git
```

Let's see what `$ADCIRC_GIT_URL` is set to. If you, while in `asgsh`, do:

```
export ADCIRC_GIT_URL=git@github.com:adcirc/
```

`initadcirc` should work,

In the latest `master`, `cloud/general/init-adcirc.sh` constructs the `git` command like this,

```
git clone ${ADCIRC_GIT_URL}/${ADCIRC_GIT_REPO}.git ${ADCIRCBASE}
```

**Comment by wwlwpd** [comment] 2021-04-14 23:29
I'll make sure the ssh URL is default in any new installations, I think it is. But you could be carrying around an old `https` based URL.

Work around:

1. open `asgsh`
2. load the profile you want
3. issue command,
`export ADCIRC_GIT_URL=git@github.com:adcirc/   # resolves issue in current profile session`
4. `save profile                                                             #  persist changes in profile`

**Comment by wwlwpd** [comment] 2021-04-20 14:45
My apologies, @jasonfleming; I discovered while working on
#454 that the default GH url was indeed `https` based. This
means that I was wrong about having fixed the default URL.
This issue will be resolved once we complete that work. Thanks!!

**Closed** 2021-04-28 23:28 UTC
Labels: answered, verify suggested workaround
